METADATA = ("title", "description", "integrations", "categories")

ALLOWED_INTEGRATIONS = (
    "asana",
    "auth0",
    "autokitteh",
    "aws",
    "calendar",
    "chatgpt",
    "confluence",
    "docs",
    "drive",
    "forms",
    "github",
    "githubcopilot",
    "gmail",
    "googlegemini",
    "height",
    "http",
    "hubspot",
    "jira",
    "linear",
    "microsoft_teams",
    "scheduler",
    "sheets",
    "slack",
    "sqlite3",
    "twilio",
    "zoom",
)

ALLOWED_CATEGORIES = (
    "AI",
    "Compliance",
    "CRM",
    "DevOps",
    "Durability",
    "Office Automation",
    "Productivity",
    "Reliability",
    "Samples",
)
