# This is an example configuration file for a PostgreSQL sample project using Autokitteh.
# It defines the project name, variables for database connection, and a trigger for executing a query
# via a webhook.

version: v1

project:
  name: postgresql_sample

  vars:
    - name: POSTGRES_HOST
      value: localhost
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DATABASE
      value: your_database_name
    - name: POSTGRES_USER
      value: your_username
    - name: POSTGRES_PASSWORD
      value: your_password

  triggers:
    - name: database_query
      type: webhook
      call: program.py:on_trigger
