# This YAML file is a declarative manifest that describes the setup of
# an AutoKitteh project that monitors comments on GitHub issues.

version: v1

project:
  name: github_issue_alert

  connections:
    - name: slack_conn
      integration: slack
    - name: github_conn
      integration: github

  triggers:
    - name: on_issue_comment
      event_type: issue_comment
      connection: GitHub_conn
      call: program.py:on_issue_comment
    - name: on_issue_created
      event_type: issues
      connection: GitHub_conn
      call: program.py:on_issue_created

  vars:
    - name: SLACK_CHANNEL
      value: GitHub_Issues
