"""Web-Based Chat UI - Multi-turn conversation with browser interface

This module implements a web-based chat interface with persistent conversation history.
Unlike the Slack-based chat, this provides a standalone web UI for AI conversations.

Architecture:
    Browser (GET) → Serve HTML + Session ID → Subscribe to webhook
    Browser (POST) → Webhook with Session → Process with history → Return response

Key Features:
    - Web-based chat interface (no Slack required)
    - Multi-turn conversations with memory
    - Durable workflow (survives server restarts)
    - Session-based conversation isolation
    - Synchronous HTTP responses for instant feedback
"""

from os import getenv
from pathlib import Path

from autokitteh import Event, get_webhook_url, http_outcome, next_event, subscribe
from autokitteh.pydantic import anthropic_pydantic_ai_provider
from pydantic_ai import Agent
from pydantic_ai.models.anthropic import AnthropicModel


# Load HTML template for the chat interface
_CHAT_HTML = Path("chat.html").read_text()

# Get webhook URL for the chat endpoint (used by browser to send messages)
_WEBHOOK_URL = get_webhook_url("chat")

# AI model configuration
_MODEL_NAME = getenv("MODEL_NAME", "claude-sonnet-4-0")

# Create Anthropic model with AutoKitteh provider
model = AnthropicModel(
    _MODEL_NAME,
    provider=anthropic_pydantic_ai_provider("anthropic")
)

# Create Pydantic AI agent with the configured model
# This agent maintains conversation context across HTTP requests
agent = Agent(
    model=model,
    instructions="Be concise, reply with one sentence.",
)


def on_start(_: Event, session_id: str) -> None:
    """Handle initial GET request and serve chat UI.

    This function is triggered when a user visits the webhook URL.
    It serves the HTML chat interface and creates a durable workflow
    to handle subsequent chat messages for this session.

    Args:
        _: AutoKitteh event (unused in this handler)
        session_id: Unique session identifier generated by AutoKitteh

    Workflow:
        1. Serve HTML with session-specific API endpoint
        2. Create subscription to chat webhook for this session
        3. Enter conversation loop:
           - Wait for POST request from browser
           - Process message with full conversation history
           - Return AI response synchronously
           - Repeat indefinitely

    HTTP Response:
        200 OK with HTML body containing embedded chat interface

    Note:
        The workflow is durable (is_durable: true in config) and persists
        even if AutoKitteh restarts. The session_id ensures each browser
        tab gets its own isolated conversation.
    """
    # Serve HTML chat interface with session-specific API endpoint embedded
    # The {{API_ENDPOINT}} placeholder is replaced with the actual webhook URL
    http_outcome(
        200,
        body=_CHAT_HTML.replace("{{API_ENDPOINT}}", f"{_WEBHOOK_URL}/{session_id}"),
    )

    # Subscribe to POST requests to the chat webhook for this specific session
    # The path_suffix filter ensures we only get messages for this conversation
    s = subscribe("chat", f"data.url.path_suffix == '{session_id}'")

    # Initialize conversation history list
    # Pydantic AI maintains this as structured message history
    history: list = []

    # Infinite loop for multi-turn conversation
    # This loop is durable and persists across AutoKitteh restarts
    while True:
        # Wait for next POST request from the browser (blocking call)
        # full=True ensures we get the complete event including event_id
        event = next_event(s, full=True)

        print(f"E: {event}")

        # Extract message text from POST body
        q = event.data.body.text

        print(f"Q: {q}")

        # Run agent with full conversation history for context
        # Pydantic AI uses this for prompt caching and context maintenance
        result = agent.run_sync(q, message_history=history)

        # Update history with all messages (including any tool calls)
        history = result.all_messages()

        # Extract the AI's response text
        a = result.output

        print(f"A: {a}")

        # Return response synchronously to the browser
        # event_id links this response to the specific HTTP request
        http_outcome(200, body=a, event_id=event.event_id)
